Add configuration to skip SRI for some files
Firesphere/silverstripe-csp-headers pull request #23
Opened 2021-05-13 04:07 UTC by matt-in-a-hat

Some external resources do not allow you to use SRI, including Google maps. See more about the reasoning here
https://stackoverflow.com/questions/39374880/sub-resource-integrity-value-for-maps-google-com-maps-api-js

2021-05-19 10:37 UTC, Firesphere requested changes

2021-05-19 10:37 UTC, Firesphere commented on src/Builders/SRIBuilder.php
> +        $skipFiles = $this->config()->get('files_to_skip_sri');
This looks like it could easily be done with in_array instead of looping all items.

2021-05-19 10:37 UTC, Firesphere commented on src/Builders/SRIBuilder.php
> +        }
Please add unit tests for your changes.

2021-05-19 10:37 UTC, Firesphere commented on readme.md
> +  files_to_skip_sri:
I feel it should be domains to skip, not files.
And a shorter key would probably be useful, e.g. `skip_domains:`

2021-05-26 04:46 UTC, matt-in-a-hat commented on src/Builders/SRIBuilder.php
> +        $skipFiles = $this->config()->get('files_to_skip_sri');
I don't think that'll let me partially match the start of the string (to allow skipping whole domains). I'm sure that would just loop the values under the hood anyway. At least this loop exits early if it matches.

2021-05-28 22:18 UTC, Firesphere commented
Coolbeans, looks good to me. Gonna merge. Thanks!

2021-05-28 22:18 UTC, merged