Allow CSP and SRI in UAT/test environments
Firesphere/silverstripe-csp-headers pull request #24
Opened 2021-05-13 04:11 UTC by matt-in-a-hat

This makes it possible to configure the module such that CSP and SRI are enabled in test environments if desired. This reduces our chance of pushing code which is otherwise tested to production to then realise it gets blocked by CSP or the SRI isn't being calculated for some reason.

Fixes #22 including the issue of depending on a group named 'administrators' which can be renamed in the CMS.

2021-05-19 10:34 UTC, Firesphere requested changes

2021-05-19 10:34 UTC, Firesphere commented on readme.md
> +    enabled: false
This would _disable_ the headers in production...

2021-05-19 10:34 UTC, Firesphere commented on src/Extensions/ControllerCSPExtension.php
> +        $this->addPolicyHeaders = ($ymlConfig['enabled'] ?? false) || static::checkCookie($owner->getRequest());
Please add some automated tests for these changes

2021-05-26 04:40 UTC, matt-in-a-hat commented on readme.md
> +    enabled: false
It's scoped to "Except" "Live", so should disable in all environments other than live.

2021-05-28 22:23 UTC, Firesphere commented on readme.md
> +    enabled: false
Yeah, nevermind, I mis-read it due to the collapsing that GitHub does.

2021-05-29 00:03 UTC, Firesphere commented
Please rebase to fix the issues?

2022-07-07 22:56 UTC, Firesphere commented
Could you please rebase this, so the automated tests will run?

2022-08-23 23:57 UTC, StephenMakrogianni commented
@matt-in-a-hat bump 🙂

2022-09-22 22:11 UTC, wilr commented
@Firesphere possible to get this re-based / merged on behalf of the poster. Be good to have this testable in test :)

2022-09-23 09:36 UTC, Firesphere commented
> @Firesphere possible to get this re-based / merged on behalf of the poster. Be good to have this testable in test :)

Maybe during the long weekend? I might... Or pull it in to this repo for a specific `dev-` tag?

2022-10-01 10:16 UTC, Firesphere commented
Okay, rebased, let's see where this leads :)

2022-10-01 10:35 UTC, Firesphere commented
@matt-in-a-hat I've rebased and fixed up the tests (I think...)

Please give it a final sanity-check?

2022-10-05 10:05 UTC, Firesphere commented
Right, gonna merge this one in and see from there. Marking as a new beta release or something

2022-10-05 10:05 UTC, merged