Add extension to automatically remove SRI on build
Firesphere/silverstripe-csp-headers pull request #25
Opened 2021-05-13 04:12 UTC by matt-in-a-hat

If this extension is applied (by adding the example yaml) then running dev/build clears out all SRI and allows them to be recalculated.

2021-05-19 10:39 UTC, Firesphere requested changes

2021-05-19 10:39 UTC, Firesphere commented on src/Extensions/SRIRefreshExtension.php
> +        foreach (SRI::get() as $item) {
`SRI::get()->deleteAll()` would do the trick.

2021-05-19 10:39 UTC, Firesphere commented on readme.md
> +To have these automatically clear out on a dev/build (useful for updating integrity hashes on production when new assets are deployed) you can apply the SRIRefreshExtension by adding the following to
I feel this would more be a config than requiring an entire extension.

2021-05-26 22:13 UTC, Firesphere requested changes

2021-05-26 22:13 UTC, Firesphere commented on src/Models/SRI.php
> +        if ($this->config()->get('clear_sri_on_build')) {
Wouldn't `SRI::get()->deleteAll()` do the trick here?

2021-05-26 22:13 UTC, Firesphere commented on src/Tasks/SRIRefreshTask.php
> +        foreach (SRI::get() as $item) {
As above, `deleteAll()` should do it

2021-05-26 22:13 UTC, Firesphere commented on src/Tasks/SRIRefreshTask.php
> +        echo "Removing SRI values...\n";
I think a BuildTask has a formatted way of outputting this?

2021-05-26 22:23 UTC, matt-in-a-hat commented on src/Models/SRI.php
> +        if ($this->config()->get('clear_sri_on_build')) {
DataList only has `removeAll`, and as far as I can see it then loads each from the database individually to delete them. This seems more efficient.

2021-05-28 22:21 UTC, Firesphere commented on src/Models/SRI.php
> +        if ($this->config()->get('clear_sri_on_build')) {
Although in theory, that makes sense, semantically, it makes more sense to me to use deleteAll(). Given this is only done during build, I don't see the need for super performance versus shorter logic

2021-05-29 00:03 UTC, Firesphere commented
Could you also please rebase?

2021-05-31 01:37 UTC, matt-in-a-hat commented
Rebased and updated to use DataList::removeAll

2021-06-09 07:55 UTC, Firesphere commented
Looks good to me. I think it only needs a rebase, so the automated tests will run. If that all passes, I can accept it in to the main branch :)

2021-07-30 07:23 UTC, merged